name: 'Webshot Archive GitHub Action'
description:
  'Uploads screenshots to Webshot Archive with visual diff detection and PR
  commenting'
author: 'webshotArchive.com'
branding:
  icon: 'docs/assets/logo.svg'
  color: 'black'

# Define your inputs here.
inputs:
  screenshotsFolder:
    description: 'Path to screenshots folder'
    required: true
    default: 'dist/cypress'

  clientId:
    description: 'API client id'
    required: true

  clientSecret:
    description: 'API client secret'
    required: true

  projectId:
    description: 'Project ID'
    required: true

  commitSha:
    description: 'The screenshot commit sha to associate with the images'

  compareCommitSha:
    description: 'A commit sha to compare with, typically the target branch'
    required: false

  branchName:
    description: 'Metadata: branch name'
    required: false

  mergedBranch:
    description: 'The branch that was merged'
    required: false

  type:
    description:
      '[DEPRECATED] this is now determined by the type of GitHub event'
    required: false

  comment:
    description: 'Should the job leave a comment on PR'
    required: false

  failedTestPattern:
    description: 'Regex pattern for failed tests'
    required: false

  tags:
    description: 'Metadata: tags ["pr"]'
    required: false
    default: ''

# Define your outputs here.
outputs:
  time:
    description: 'none'

runs:
  using: node20
  main: dist/index.js
